fraud_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DB_SCHEMA', 'fraud_detection') }}"
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT', '8123') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'password') }}"
