FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances pour la Data Science
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie du script d'entraînement
COPY train.py .

# La commande par défaut lance l'entraînement
CMD ["python", "train.py"]
