FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

# On expose le port 8000 pour que le monde extérieur puisse interroger l'API
EXPOSE 8000

# On lance le serveur Uvicorn qui héberge l'application FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
